### ISSUE TITLE
PUBLIC SALE - Decarbonized - Project February 2024

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-metadata#5]
# **Project Data**
---
## **Generic Project Data**
- [ ] Project name : 
- [ ] description : 
- [ ] Project developer :
- [ ] Certifier :
- [ ] Project area (ha) :
- [ ] Country : 
- [ ] End date : 
- [ ] Project color (Green, Blue, Brown) : 
- [ ] Project type (Forest, mangrove, etc...) : 
- [ ] Project category (Regeneration, Conservation) : 
- [ ] Status : Upcoming
- [ ] Source (Carbonable, Other) : Carbonable

## **Project Carbon Data**
- [ ] Total Project estimated carbon units (t) : 
- [ ] Asset's avg. annual capacity (t/y) : 
- [ ] Absorption curve : 

## **Supply Project**
- [ ] Currency (EUR, USD, ETH, etc..) : 
- [ ] Value match (ex: 1 value = 1 $) : 
- [ ] Max supply : 
- [ ] Reserve supply (Airdrop) : 
- [ ] Whitelist supply : 
- [ ] Public supply : 

## **Img Project**
- [ ] SFT img : 
- [ ] Collection img : 

# **Project On-Chain**
---
- [ ] Project SFT address : 
- [ ] Project SFT slot : 
- [ ] Minter address : 
- [ ] Offseter address : 
- [ ] Yielder address :

**Comment by Khyati729** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-Tech-Team-workspace-64527a8c74b9f900123e10f6/issues/Carbonable/carbonable-metadata/5?planning-poker) with Zenhub @cloudvenger
