### ISSUE TITLE
PUBLIC SALE - Design the SVG for the sale of the new Project

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-metadata#7]
**Description**
---

Design the SVG for the sale of the new Project

**Comment by G2CARBZ** [comment]
NOTA BENE
Data which needs clarification / to be finalized: 
* Number of hectares needs (i.e. is it the first milestone? Or the total? Or will it be dynamic?)
* Number of tons (same question as above)
* SDGs: I personally need to confirm which one we go with

[Uploading... Karatharu.svg]

**Comment by G2CARBZ** [comment]
Figma link: https://www.figma.com/file/TxyvqO53GlCiTaJOE26AwM/dApp?type=design&node-id=5535%3A81624&mode=design&t=gYkfmTxBOtOOyrPN-1

**Comment by Khyati729** [comment]
@G2CARBZ 
Missing portions
-Description of the project

**Comment by G2CARBZ** [comment]
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejc4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f980f3c3c104d8075131a44725327c0ee58431a0/52633053_2187678071560991_23696945184768000_n.jpeg" alt="52633053_2187678071560991_23696945184768000_n.jpeg" />
